version: "3"
services:
  web:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ${PROJECT_PATH}:/work
      - ./logs:/var/log/nginx
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
