version: "3"
services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ${PROJECT_PATH}:/work
      - ./logs:/var/log/nginx
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf

  composer:
    build: ./docker/composer
    volumes:
      - ${PROJECT_PATH}:/work
    working_dir: /work
